default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ObjectCannon_development

test:
  <<: *default
  database: ObjectCannon_test

production:
  <<: *default
  database: ObjectCannon_production
  username: ObjectCannon
  password: <%= ENV['OBJECTCANNON_DATABASE_PASSWORD'] %>
